steps:
  # Step 1: Create a Compilation Result
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e -o pipefail

        TOKEN=$(gcloud auth print-access-token)

        RELEASE_CONFIG_RESOURCE="projects/${_PROJECT_ID}/locations/${_DATAFORM_LOCATION}/repositories/${_DATAFORM_REPO_ID}/releaseConfigs/${_RELEASE_CONFIG_ID}"
        COMPILATION_RESULTS_API="https://invalid.googleapis.com/v1/projects/${_PROJECT_ID}/locations/${_DATAFORM_LOCATION}/repositories/${_DATAFORM_REPO_ID}/compilationResults"

        CREATE_PAYLOAD="{\"releaseConfig\": \"$$RELEASE_CONFIG_RESOURCE\"}"

        echo "Creating compilation result..."

        curl \
          --fail-with-body \
          --retry 3 \
          --retry-delay 2 \
          --retry-max-time 60 \
          -X POST \
          -H "Authorization: Bearer $$TOKEN" \
          -H "Content-Type: application/json" \
          -d "$$CREATE_PAYLOAD" \
          "$$COMPILATION_RESULTS_API" \
          | tee /workspace/compilation_response.json

  # Step 2: Read Compilation Result
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        set -e

        apk add --no-cache jq

        COMPILATION_NAME=$(jq -r '.name' < /workspace/compilation_response.json)

        echo "Compilation Result:"
        echo $$COMPILATION_NAME

        echo $$COMPILATION_NAME > /workspace/compilation_result_name.txt

  # Step 3: Update Release Config
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        COMPILATION_NAME=$(cat /workspace/compilation_result_name.txt)

        RELEASE_CONFIG_RESOURCE="projects/${_PROJECT_ID}/locations/${_DATAFORM_LOCATION}/repositories/${_DATAFORM_REPO_ID}/releaseConfigs/${_RELEASE_CONFIG_ID}"

        PATCH_PAYLOAD="{\"releaseCompilationResult\":\"$$COMPILATION_NAME\",\"gitCommitish\":\"$BRANCH_NAME\"}"

        RELEASE_CONFIG_PATCH_API="https://dataform.googleapis.com/v1/$${RELEASE_CONFIG_RESOURCE}"

        echo "Updating Release Config..."

        curl \
          --fail-with-body \
          --retry 3 \
          --retry-delay 2 \
          --retry-max-time 60 \
          -X PATCH \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d "$$PATCH_PAYLOAD" \
          "$$RELEASE_CONFIG_PATCH_API?updateMask=releaseCompilationResult"

  # Step 4: Invoke Workflow Config
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        WORKFLOW_CONFIG_RESOURCE="projects/${_PROJECT_ID}/locations/${_DATAFORM_LOCATION}/repositories/${_DATAFORM_REPO_ID}/workflowConfigs/${_WORKFLOW_CONFIG_ID}"

        CREATE_WORKFLOW_PAYLOAD="{\"workflowConfig\":\"$$WORKFLOW_CONFIG_RESOURCE\"}"

        WORKFLOW_INVOCATIONS_API="https://dataform.googleapis.com/v1/projects/${_PROJECT_ID}/locations/${_DATAFORM_LOCATION}/repositories/${_DATAFORM_REPO_ID}/workflowInvocations"

        echo "Invoking Workflow Config..."

        curl \
          --fail-with-body \
          --retry 3 \
          --retry-delay 2 \
          --retry-max-time 60 \
          -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          -d "$$CREATE_WORKFLOW_PAYLOAD" \
          "$$WORKFLOW_INVOCATIONS_API"

        echo "Workflow Invocation created successfully."

substitutions:
  _DATAFORM_LOCATION: us-central1
  _DATAFORM_REPO_ID: ''
  _RELEASE_CONFIG_ID: ''
  _WORKFLOW_CONFIG_ID: ''
  _PROJECT_ID: ${PROJECT_ID}

options:
  logging: CLOUD_LOGGING_ONLY